In [3]:
import pandas as pd
import numpy as np
import csv
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn import preprocessing
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder

In [17]:
data = pd.read_csv("C:/train_data.csv")
data = data.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
data

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911,0-10
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954,41-50
2,3,10,e,1,X,2,anesthesia,S,E,2.0,31397,7.0,Trauma,Extreme,2,51-60,4745,31-40
3,4,26,b,2,Y,2,radiotherapy,R,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,7272,41-50
4,5,26,b,2,Y,2,radiotherapy,S,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,5558,41-50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318433,318434,6,a,6,X,3,radiotherapy,Q,F,4.0,86499,23.0,Emergency,Moderate,3,41-50,4144,20-Nov
318434,318435,24,a,1,X,2,anesthesia,Q,E,4.0,325,8.0,Urgent,Moderate,4,81-90,6699,31-40
318435,318436,7,a,4,X,3,gynecology,R,F,4.0,125235,10.0,Emergency,Minor,3,71-80,4235,20-Nov
318436,318437,11,b,2,Y,3,anesthesia,Q,D,3.0,91081,8.0,Trauma,Minor,5,20-Nov,3761,20-Nov
318437,318438,19,a,7,Y,5,gynecology,Q,C,2.0,21641,8.0,Emergency,Minor,2,20-Nov,4752,0-10

In [18]:
data = data.drop(["case_id","Hospital_code","Hospital_type_code","City_Code_Hospital","Hospital_region_code","Department","Ward_Type","Ward_Facility_Code","patientid","Type of Admission"],axis = 1)
data['Available Extra Rooms in Hospital'] = data['Available Extra Rooms in Hospital'].astype(float)
data['Visitors with Patient'] = data['Visitors with Patient'].astype(float)
data['Admission_Deposit'] = data['Admission_Deposit'].astype(float)
labelencoder = LabelEncoder()
data.iloc[:,3] = labelencoder.fit_transform(data.iloc[:,3])
data.iloc[:,5] = labelencoder.fit_transform(data.iloc[:,5])
data.iloc[:,7] = labelencoder.fit_transform(data.iloc[:,7])
data

,Available Extra Rooms in Hospital,Bed Grade,City_Code_Patient,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,3.0,2.0,7.0,0,2.0,5,4911.0,0
1,2.0,2.0,7.0,0,2.0,5,5954.0,4
2,2.0,2.0,7.0,0,2.0,5,4745.0,3
3,2.0,2.0,7.0,0,2.0,5,7272.0,4
4,2.0,2.0,7.0,0,2.0,5,5558.0,4
...,...,...,...,...,...,...,...,...
318433,3.0,4.0,23.0,2,3.0,4,4144.0,1
318434,2.0,4.0,8.0,2,4.0,8,6699.0,3
318435,3.0,4.0,10.0,1,3.0,7,4235.0,1
318436,3.0,3.0,8.0,1,5.0,1,3761.0,1
318437,5.0,2.0,8.0,1,2.0,1,4752.0,0

In [19]:
features=data.iloc[:,range(0,7)]
respond=data.iloc[:,-1]

In [20]:
X_train, X_test, y_train, y_test = train_test_split(features, respond, test_size=0.3)

# use sklearn.preprocessing.StandardScaler to standardize predictors 
scaledData = StandardScaler()
X_train = scaledData.fit_transform(X_train)
X_test = scaledData.fit_transform(X_test)

In [21]:
data[:] = np.nan_to_num(data)
data

,Available Extra Rooms in Hospital,Bed Grade,City_Code_Patient,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,3.0,2.0,7.0,0.0,2.0,5.0,4911.0,0.0
1,2.0,2.0,7.0,0.0,2.0,5.0,5954.0,4.0
2,2.0,2.0,7.0,0.0,2.0,5.0,4745.0,3.0
3,2.0,2.0,7.0,0.0,2.0,5.0,7272.0,4.0
4,2.0,2.0,7.0,0.0,2.0,5.0,5558.0,4.0
...,...,...,...,...,...,...,...,...
318433,3.0,4.0,23.0,2.0,3.0,4.0,4144.0,1.0
318434,2.0,4.0,8.0,2.0,4.0,8.0,6699.0,3.0
318435,3.0,4.0,10.0,1.0,3.0,7.0,4235.0,1.0
318436,3.0,3.0,8.0,1.0,5.0,1.0,3761.0,1.0
318437,5.0,2.0,8.0,1.0,2.0,1.0,4752.0,0.0

In [ ]:
def KNN(k):
    clf = neighbors.KNeighborsClassifier(k)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    score = accuracy_score(y_test,y_pred)
    confusion_matrix(y_pred, y_test)

    #Plot confusion matrix
    cm = confusion_matrix(y_pred, y_test)
    df_cm = pd.DataFrame(cm)
    sns.set(font_scale=1.2) # for label size
    sns.heatmap(df_cm, annot=True, annot_kws={"size": 12}) # font size
    plt.show()
    
    #Print classification report
    cls = classification_report(y_test, y_pred)
    print(cls)
    return score
KNN(40)

In [11]:
data.Stay.value_counts()

2     86316
1     77095
3     54312
5     34463
0     23250
4     11541
7     10096
10     6548
8      4761
9      2713
6      2698
Name: Stay, dtype: int64

In [13]:
data.patientid.value_counts()

66714     50
91292     43
38525     39
101359    36
33491     34
          ..
24426      1
22379      1
42869      1
25287      1
58524      1
Name: patientid, Length: 90344, dtype: int64